databases:
  - name: gorila-db
    databaseName: gorila_motos
    user: gorila_user
    plan: free
    region: virginia

services:
  - type: web
    name: backend-gorila_motos
    runtime: docker
    plan: free
    region: virginia
    branch: main
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        fromDatabase:
          name: gorila-db
          property: connectionString
      - key: DB_PASSWORD
        fromDatabase:
          name: gorila-db
          property: password
      - key: DB_USER
        fromDatabase:
          name: gorila-db
          property: user
      - key: ALLOWED_ORIGINS
        value: https://gorila-motos.vercel.app
      - key: SUPABASE_URL
        value: https://rsztjwgbgljjkrnrpbxi.supabase.co
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: JWT_EXPIRATION_MINUTES
        value: "120"
      - key: GITLAB_ENABLED
        value: "false"
